url: "https://www.tiny.cloud"
permalink: pretty
origin: "https://www.tiny.cloud"
baseurl: ""
shared_baseurl: ""
syntax_highlight_theme: "tomorrow-night"
cdnurl: "https://cloud.tinymce.com/stable/tinymce.min.js"
default_meta_keywords: tinymce, documentation, docs, plugins, customizable skins, configuration, examples, html, php, java, javascript, image editor, inline editor, distraction-free editor, classic editor

exclude:
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - wercker.yml
  - node_modules
  - .idea
  - .git

markdown: redcarpet

redcarpet:
  extensions:
    - autolink
    - no_intra_emphasis
    - tables
    - prettify

plugins:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap
